runtime: python37
instance_class: F2

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static
- url: /template
  static_dir: template

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

automatic_scaling:
  # This parameter specifies the CPU usage threshold at which new instances 
  # will be started to handle traffic,
  target_cpu_utilization: 0.7
  min_instances: 1
  max_instances: 5
  # The minimum amount of time that App Engine should allow a request to wait in 
  # the pending queue before starting a new instance to handle it. When this 
  # threshold is reached, it is a signal to scale down, and results in a decrease 
  # in the number of instances. 
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 25



