runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT api:app
instance_class: F2

runtime_config:
  python_version: 3.7
resources:
     cpu: 2
     memory_gb: 8.0
     disk_size_gb: 20
automatic_scaling:
  max_concurrent_requests: 25

handlers:
  - url : /updatebrands
    script : update_brands.sh

beta_settings:
  cloud_sql_instances: frenzynlp:us-central1:brands