runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT api:app
instance_class: F2

runtime_config:
  python_version: 3.7
resources:
     cpu: 2
     memory_gb: 8.0
     disk_size_gb: 20
health_check:
      enable_health_check: True
automatic_scaling:
  max_concurrent_requests: 25

